"""Add torrent_hash to MediaRequest model

Revision ID: 9d8b6b876588
Revises: e6db40fc6126
Create Date: 2024-11-30 13:29:51.400291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d8b6b876588'
down_revision = 'e6db40fc6126'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('torrent_hash', sa.String(length=40), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.drop_column('torrent_hash')

    # ### end Alembic commands ###
