"""Add torrent link, save path, and progress to MediaRequest

Revision ID: e6db40fc6126
Revises: 77b6ea61fda2
Create Date: 2024-11-30 08:52:30.248341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6db40fc6126'
down_revision = '77b6ea61fda2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('torrent_link', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('save_path', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('progress', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.drop_column('progress')
        batch_op.drop_column('save_path')
        batch_op.drop_column('torrent_link')

    # ### end Alembic commands ###
